### PR TITLE
Fix artifact project

### LINKED ISSUE #94: Incorrect value for project when inspecting an artifact
## Steps to reproduce

On a fresh playground with a bobfile containing:

```yaml
project: customName
```

1. Run `bob clean` to make sure all artifacts are cleared. You can validate that artifacts are cleared by running  `ls ~/.bobcache/artifacts` and checking that the directory is empty.
2. Run `bob build` to create an artifact. Get the artifact id from `ls ~/.bobcache/artifacts`. 
3. Inspect the artifact. Ex. `bob inspect artifact --id 83b9c10614d67dbf`

**Output**:

```bash
Artifact Info
  targets:
    targets/run
  metadata:
    taskname: build
    inputHash: 83b9c10614d67dbf
    project: /home/andrei/testare
    createdAt: 06 Jun 22 14:01 +0300
    targetType: path
```

**Desired Output**:

```
Artifact Info
  targets:
    targets/run
  metadata:
    taskname: build
    inputHash: 83b9c10614d67dbf
    project: customName
    createdAt: 06 Jun 22 14:01 +0300
    targetType: path
```

The project should equal `customName` not  `/home/andrei/testare`.  `/home/andrei/testare` should be set only if project is missing from bobfile.

### PR DESCRIPTION
**Pull request by zuzuleinen**
TODO:

- [ ] add test to assure project name is set correctly for all tasks in an aggregate.

closes #94

### CODE REVIEW

**Comment by Equanox** [comment]
@zuzuleinen this behavior should be assured. Would be nice to have a test which checks that the projectname is set correctly for all tasks with local & remote repositories.

**Review by Equanox — CHANGES_REQUESTED** [review]
@zuzuleinen this behavior should be assured. Would be nice to have a test which checks that the projectname is set correctly for all tasks in a aggregate with local & remote repositories.

File: test/e2e/project/project_test.go [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+var _ = Describe("Testing project name for tats", func() {
+	Context("when project name is not set", func() {
+		It("all tasks should contain working dir", func() {
+			useBobFile("without_project_name")
+			defer releaseBobfile("without_project_name")
+
+			b, err := Bob()
+			Expect(err).NotTo(HaveOccurred())
+
+			ag, err := b.AggregateSparse()
```
Comment (Equanox) [inline test/e2e/project/project_test.go:19]: Can you write those test that both Aggregate() + AggregateSparse() are tested? Will make me sleep better at night.

**Review by Equanox — APPROVED** [review]
